import { Emprendedor } from "./emprendedor.model";

// Datos de ejemplo para usar durante desarrollo o cuando la API no esté disponible
export const EMPRENDEDORES_MOCK: Emprendedor[] = [
  {
    id: 1,
    nombre: "Familia Mamani",
    tipo_servicio: "Hospedaje",
    descripcion: "Visitar a la familia Mamani es sumergirse en la calidez de un hogar tradicional andino donde cada sonrisa te abraza. Su compromiso con la cultura y la naturaleza convierte cada momento en una experiencia inolvidable.",
    ubicacion: "Isla Amantani",
    telefono: "987654321",
    email: "mamani@ejemplo.com",
    pagina_web: "https://mamani.ejemplo.com",
    horario_atencion: "Todos los días: 8:00 am - 8:00 pm",
    precio_rango: "S/. 50.00 - S/. 150.00",
    metodos_pago: ["Efectivo", "Transferencia"],
    capacidad_aforo: 10,
    numero_personas_atiende: 8,
    comentarios_resenas: "Excelente atención y ambientación cultural",
    imagenes: ["url/mamani1.jpg", "url/mamani2.jpg"],
    categoria: "Hospedaje",
    certificaciones: ["Turismo Rural Comunitario"],
    idiomas_hablados: ["Español", "Quechua", "Inglés básico"],
    opciones_acceso: "Bote desde Puno",
    facilidades_discapacidad: false
  },
  {
    id: 2,
    nombre: "Familia Apaza",
    tipo_servicio: "Gastronomía",
    descripcion: "La familia Apaza es conocida por su gastronomía auténtica que utiliza ingredientes como la quinua, habas, y papas nativas cultivadas en su propia tierra. Además, han abierto un pequeño museo en su casa con reliquias prehispánicas.",
    ubicacion: "Isla Tikonata",
    telefono: "987654322",
    email: "apaza@ejemplo.com",
    pagina_web: "https://apaza.ejemplo.com",
    horario_atencion: "Lunes a Domingo: 9:00 am - 7:00 pm",
    precio_rango: "S/. 30.00 - S/. 100.00",
    metodos_pago: ["Efectivo", "Yape"],
    capacidad_aforo: 15,
    numero_personas_atiende: 10,
    comentarios_resenas: "Comida exquisita y auténtica",
    imagenes: ["url/apaza1.jpg", "url/apaza2.jpg"],
    categoria: "Gastronomía",
    certificaciones: ["Cocina Tradicional Andina"],
    idiomas_hablados: ["Español", "Quechua"],
    opciones_acceso: "Lancha desde Capachica",
    facilidades_discapacidad: true
  },
  {
    id: 3,
    nombre: "Familia Quispe",
    tipo_servicio: "Artesanía",
    descripcion: "La familia Quispe ha cultivado una gran pasión por la artesanía textil durante generaciones. Su taller está lleno de hermosos bordados y tejidos a mano que representan los colores y patrones de la región andina.",
    ubicacion: "Llachón",
    telefono: "987654323",
    email: "quispe@ejemplo.com",
    pagina_web: "https://quispe.ejemplo.com",
    horario_atencion: "Martes a Domingo: 10:00 am - 6:00 pm",
    precio_rango: "S/. 20.00 - S/. 200.00",
    metodos_pago: ["Efectivo", "Tarjeta"],
    capacidad_aforo: 8,
    numero_personas_atiende: 6,
    comentarios_resenas: "Artesanías de altísima calidad",
    imagenes: ["url/quispe1.jpg", "url/quispe2.jpg"],
    categoria: "Artesanía",
    certificaciones: ["Artesanía Tradicional Certificada"],
    idiomas_hablados: ["Español", "Quechua", "Aymara"],
    opciones_acceso: "Transporte terrestre",
    facilidades_discapacidad: false
  }
];